version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/src/app
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: ./backend2
  #     dockerfile: Dockerfile
  #   container_name: backend2
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend2:/usr/src/app

  minio:
    image: minio/minio
    ports:
      - "9001:9001" # Console
      - "9000:9000" # S3-API
    environment:
      - MINIO_ACCESS_KEY=wonrada
      - MINIO_SECRET_KEY=wonrada1
    command: server --address "0.0.0.0:9000" --console-address "0.0.0.0:9001" /data
    volumes:
      - ./minio/.data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      apk add nc &&
      while ! nc -z minio 9000; do echo 'Wait minio to startup...' && sleep 0.1; done; sleep 5 &&
      /usr/bin/mc config host add myminio http://minio:9000 wonrada wonrada1;
      /usr/bin/mc mb myminio/wonrada-bugket;
      /usr/bin/mc policy download myminio/wonrada-bugket;
      exit 0;
      "